package HCaptchaSolver

import (
	"fmt"
	"github.com/justtaldevelops/hcaptcha-solver-go/algorithm"
	"testing"
)

// TestCaptcha ...
func TestCaptcha(t *testing.T) {
	fmt.Println(algorithm.Solve("hsl", "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzIjoyLCJ0IjoicCIsImQiOiJwMDFXWVZyVzZjRkl3VVNiV05paUdrQ015VmFnOFZkY2FWUzBPVGFaaDM1VnRnS2M1MlduWXM3SkdPajN5MGtHZHdNNi9ZMmQyN2I2c3BIWmlCSjVvdVZMMWNySHduN2RmMStzUjZTUDhDdU9DcEtpM3JLRFIwSlNDc25wSXVjamFVbGd1enpYTXkzakl4d0t3U0RucXQ0MG1EWEZoU0RiMjdLNDBWU3QvRXFrbXNEOVRzQWowRGJXTFE9PW5zdGVPcDlxdXdqY2xOcEwiLCJsIjoiaHR0cHM6Ly9hc3NldHMuaGNhcHRjaGEuY29tL2MvNTgyOTZiODAiLCJlIjoxNjE3NTU0Nzg0fQ.IHACH-J48Dhzd1Lz0STv5wjZKipMzRg5A-DD71n3WEM"))
	fmt.Println(algorithm.Solve("hsw", "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzIjoyLCJ0IjoidyIsImQiOiJmTkRxeWt2WUxRWkRNemlrd2Zwc1VMbHUrcklpMXlYejNnYjdNRUhDWEM2TGhFRFIzMFo1VzkwRExvcFhTWHFUcjFrT1E1bDQ1VHBaSzBDY2pnZlhEWHVmL3pIRjliQ3RIdjhiTEtsekM2TUlWbzB0a28zT052SlU2U1A3NkdCdVNwV0pCTU1jRVAyTzQ5aXpTM3VMc1MyK0NFQVRiTW1kczBNSHFyY3NWNXFUL0hWL3pjdUZmbWpXMkE9PTVFWXlVbHR2TlAzbmxFUFgiLCJsIjoiaHR0cHM6Ly9uZXdhc3NldHMuaGNhcHRjaGEuY29tL2MvOTYzZTQ2YjciLCJlIjoxNjM2Mjk5OTkxfQ.g_xb9oJD-antRtIXq-CW7Mf3lzOzin4CPvd8uU2O6Jg"))
}
